name: incrementally_loading_listview_example
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  incrementally_loading_listview:
    path: ../
  pedantic: ^1.8.0

flutter:
  uses-material-design: true